---
- name: Install and configure Pi-Hole
  hosts: piholes
  become: yes

  tasks:
    - name: Install software
      apt:
        name: ['vim', 'git', 'ufw']
        state: present
      tags: software

    - name: Deny everything and enable UFW
      ufw:
        state: enabled
        policy: deny
      tags: ufw

    - name: Allow OpenSSH
      ufw:
        rule: allow
        name: ssh
      tags: ufw

    - name: Allow HTTP and HTTPS
      ufw:
        rule: allow
        port: '80,443'
        proto: tcp
      tags: ufw

    - name: Allow access to port 53
      ufw:
        rule: allow
        port: '53'
      tags: ufw

    - name: Clone whitelist script
      git:
        repo: "https://github.com/anudeepND/whitelist.git"
        dest: /opt/whitelist
        update: yes
      tags: pihole

    - name: Create crontab entry to run whitelist.sh
      cron:
        name: Update Pi-Hole whitelist
        special_time: daily
        user: root
        job: "/opt/whitelist/scripts/whitelist.sh"
      tags: pihole
