---
- name: Install and configure Pi-Hole
  hosts: piholes
  become: yes

  tasks:
    - name: Install software
      apt:
        name: ['vim', 'git', 'ufw']
        state: present
      tags: software

    - name: Configure UFW
      include_tasks: tasks/ufw.yml
      tags: ufw

    - name: Configure Pi-Hole Whitelist 
      include_tasks: tasks/whitelist.yml
      tags: pihole
