---
- name: Deny everything and enable UFW
  ufw:
    state: enabled
    policy: deny
  tags: ufw

- name: Allow OpenSSH
  ufw:
    rule: allow
    name: ssh
  tags: ufw

- name: Allow HTTP and HTTPS
  ufw:
    rule: allow
    port: '80,443'
    proto: tcp
  tags: ufw

- name: Allow access to port 53
  ufw:
    rule: allow
    port: '53'
  tags: ufw

